/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import org.junit.jupiter.api.*;
import org.junit.jupiter.api.extension.MediaType;

import java.nio.file.Files;

import static org.junit.jupiter.api.Assertions.*;

class LibraryTest {
    LibraryTest(TestReporter testReporter) {
        testReporter.publishEntry("constructor", "value1");
        // Publish a file at the class level
        testReporter.publishFile("constructor.json", MediaType.APPLICATION_JSON, path -> {
            Files.writeString(path, "{ constructor: [] }");
        });
    }

    @BeforeEach
    public void beforeEach(TestReporter testReporter) {
        testReporter.publishEntry("beforeEach", "value2");
        // Publish a text file before the test
        testReporter.publishFile("beforeEach.txt", MediaType.TEXT_PLAIN, path -> {
            Files.writeString(path, "Hello world");
        });
    }

    @Test
    void someLibraryMethodReturnsTrue(TestReporter testReporter) {
        testReporter.publishEntry("test", "value3");
        // Publish an image during the test
        testReporter.publishFile("test.svg", MediaType.create("image", "svg+xml"), path -> {
            Files.writeString(path, "<svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 800 600\"><rect width=\"800\" height=\"600\" fill=\"#F5F5F0\"/><rect width=\"350\" height=\"600\" fill=\"#D4292E\"/><rect x=\"350\" width=\"450\" height=\"250\" fill=\"#1356A3\"/><rect x=\"350\" y=\"250\" width=\"200\" height=\"350\" fill=\"#F7D838\"/><rect x=\"550\" y=\"250\" width=\"250\" height=\"350\" fill=\"#F5F5F0\"/><line x1=\"350\" y1=\"0\" x2=\"350\" y2=\"600\" stroke=\"#1A1A1A\" stroke-width=\"12\"/><line x1=\"350\" y1=\"250\" x2=\"800\" y2=\"250\" stroke=\"#1A1A1A\" stroke-width=\"12\"/><line x1=\"550\" y1=\"250\" x2=\"550\" y2=\"600\" stroke=\"#1A1A1A\" stroke-width=\"12\"/><rect width=\"800\" height=\"600\" fill=\"none\" stroke=\"#1A1A1A\" stroke-width=\"14\"/></svg>");
        });

        Library classUnderTest = new Library();
        assertTrue(classUnderTest.someLibraryMethod(), "someLibraryMethod should return 'true'");
    }

    @AfterEach
    public void afterEach(TestReporter testReporter) {
        testReporter.publishEntry("afterEach", "value4");
        // Publish a (fake) video file after the test
        testReporter.publishFile("afterEach.mp4", MediaType.create("video", "mp4"), path -> {
            Files.writeString(path, "This is just a text file that pretends to be a video.");
        });
    }
}
