/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import org.junit.jupiter.api.*;

import static org.junit.jupiter.api.Assertions.*;

class LibraryTest {
    LibraryTest(TestReporter testReporter) {
        testReporter.publishEntry("constructor", "value1");
    }

    @BeforeEach
    public void beforeEach(TestReporter testReporter) {
        testReporter.publishEntry("beforeEach", "value2");
    }

    @Test
    void someLibraryMethodReturnsTrue(TestReporter testReporter) {
        testReporter.publishEntry("test", "value3");

        Library classUnderTest = new Library();
        assertTrue(classUnderTest.someLibraryMethod(), "someLibraryMethod should return 'true'");
    }

    @AfterEach
    public void afterEach(TestReporter testReporter) {
        testReporter.publishEntry("afterEach", "value4");
    }
}
